### ISSUE TITLE
Intro to Containers, Launching a Docker App on Atmosphere, & Advanced Docker 

### ISSUE THREAD

**Issue by rbartelme** [CyVerse-learning-materials/foss#28]
# Intro to Containers

- [ ] Simplify Kubernetes, it's really just container management/orchestration
- [ ] Need to confirm that we will be launching atmo for the demos?? @JasonJWilliamsNY?

# Launching a Docker App on Atmosphere

- [ ] Keep or remove Launching a Docker App on Atmosphere depending on whether we will use this platform

# Advanced Docker

- [ ] Leave in place for self study or experimentation? 
- [x] Or Remove?

**Comment by rbartelme** [comment]
- [ ] Fix Github Repository link to point to this repo's `.rst` location

**Comment by JasonJWilliamsNY** [comment]
I think we should talk with Nirav about will we use Atmosphere (or possibly JetStream) for teaching with containers.
